### ISSUE TITLE
What should the syntax for @use without a namespace be?

### ISSUE THREAD

**Issue by nex3** [sass/language#10]
Although we want to encourage users to use namespaces for most of their modules, there are valid use-cases for avoiding namespaces, such as importing a legacy library that already uses manual namespace. Draft 2 defines the syntax for doing this as `@use "susy" no-prefix`, but I'm not thrilled with this. The term "prefix" is a holdover from when namespaces just added to the identifier rather than using a `.` to separate names (`susy-foo` versus `susy.foo`), and if possible I'd like the syntax to more closely mirror that of choosing a prefix (`@use "susy" as grid`).

## Possible Options

1. ### Keep the existing syntax

   ```scss
   @use "susy" no-prefix;
   ```

2. ### Use another keyword

   ```scss
   @use "susy" no-namespace; // Kind of wordy
   @use "susy" global; // "global" isn't really accurate; it's scoped to this module
   ```

3. ### Mirror the explicit namespace syntax

   ```scss
   @use "susy" as *;
   ```

**Comment by olivierbossel** [comment]
I'll vote also for the option 3. It's more precise and as  @TedSander says, just awkward enough to avoid to much use of this feature.

**Comment by nex3** [comment]
Option 3 is also my preference, and the option I included in Draft 3. I'll close this out for now, although if anyone has a strong alternate opinion feel free to comment and we can continue discussing.
