### ISSUE TITLE
Selector Rewriting

### ISSUE THREAD

**Issue by chriseppstein** [sass/language#2]
Should the new module system have a selector rewriting capability?

https://github.com/sass/sass/issues/2024

**Comment by nex3** [comment]
I think this falls under the "extend-only imports" non-goal. If we had that, you'd be able to write something like

``` scss
// _button.scss
.buttonComponent {
  // ...
}
```

``` scss
// app.scss
@use "button" extend-only;

.btn {
  @extend .buttonComponent;
}
```

and get the behavior you want.

Alternately, if you just want to scope the existing selectors, you can do that in the current proposal:

``` scss
// _button.scss
.buttonComponent {
  // ...
}
```

``` scss
// app.scss
@use "button" mixin;

.btn {
  @include button;
}
```

Either way, I don't think the proposal should be extended to include specific support for this use case.
