### ISSUE TITLE
Will it be possible to export/forward members starting in `_` or `-`?

### ISSUE THREAD

**Issue by mirisuzanne** [sass/language#22]
I'm working on a tool to help manage css variables, and we've been considering e.g. `@mixin --color()` to reflect the custom property syntax. If I understand right, that would be considered a private function by the new module proposal. How strict is that rule, and can it be overridden?

I'm not sure this warrants a "feature request" as much as an answer. I was curious, and wondered what you're thinking.

**Comment by nex3** [comment]
The plan is not to allow this. We could add an explicit exception for `--` though, if you'd like.

**Comment by mirisuzanne** [comment]
I'd use it if it's available, but only if that exception makes sense for the language. It is a useful way to reference css custom properties.

**Comment by nex3** [comment]
I think I'll leave it as-is for now. We can always add this exception later if people ask for it.
