### ISSUE TITLE
Setting config for a common module referenced by other modules

### ISSUE THREAD

**Issue by kfranqueiro** [sass/language#23]
## Background

[MDC Web](https://github.com/material-components/material-components-web) has a theme package, which contains a set of `!default` global theme variables that make it possible to quickly change the primary/secondary color in a page/app. The rest of MDC Web's components then reference these variables within their own individual `scss` files.

e.g.:

```scss
$mdc-theme-primary: #fedbd0;
$mdc-theme-secondary: #feeae6;

@import '@material/button/mdc-button';
@import '@material/checkbox/mdc-checkbox';
...
```

## Question

Does the configuration passed with the first `@use` effectively "win" for subsequent `@use`s of the same module (given that modules should only be loaded once, and given the shared `!default` syntax)? Or does each `@use` start from scratch?

e.g. can I accomplish the same as above by doing this?

```scss
@use '@material/theme/variables' with (
  primary: #fedbd0,
  secondary: #feeae6
);

@use '@material/button/mdc-button';
@use '@material/checkbox/mdc-checkbox';
```

i.e., will other subsequent internal `@use`s of MDC's theme code (e.g. within MDC Button and Checkbox above) inherit the values from my `with`, akin to how `!default` global variables work? Or would we somehow need to be able to relay this configuration to every direct and transitive MDC import? (Or, if all else fails, would we be better off continuing to rely on global variables for MDC's case?...)

**Comment by nex3** [comment]
In order for a module to be loaded with a configuration, it must never have been loaded before. Then, that configuration applies to all subsequent uses of that module (which must not have their own configurations).

An earlier draft worked differently, and allowed the same module to be loaded multiple times with different configurations. But this ended up being pretty confusing in the cases you bring up.

Let me know if you need more clarification!

**Comment by kfranqueiro** [comment]
Thanks for the clarification!

This means that at the very least, we will need to document how to override our variables via `@use`ing our `variables` partials before importing anything that emits styles - especially any `variables` partials that are effective across packages, e.g. `mdc-theme`.

One follow-up question, regarding significance of ordering: let's say that we have a `@mixin` in our `mixins` partial that specifies a default value for an argument that references a variable in our `variables` partial. e.g.:

```scss
// some-lib/_mixins.scss
@use  './variables';

@mixin cool-thing($foo: $variables.foo) {
  color: $foo;
}
```

```scss
// some-lib/_variables.scss
$foo: #000 !default;
```

Does that default value only get resolved at the time the `@mixin` is `@include`d? i.e. if someone does this:

```scss
@use 'some-lib/mixins' as lib-mixins;
@use 'some-lib/variables' with (
  $foo: #fff
);

.some-class {
  @include lib-mixins.cool-thing;
}
```

Will this result in `.some-class { color: #fff }` (i.e. using the `with` value even though `mixins` was `@use`d before `variables`), or `.some-class { color: #000 }`?

**Comment by nex3** [comment]
> This means that at the very least, we will need to document how to override our variables via `@use`ing our `variables` partials before importing anything that emits styles - especially any `variables` partials that are effective across packages, e.g. `mdc-theme`.

Another option would be to forward the variables module through each module a user is expected to import, so they could write:

```scss
@use 'some-lib/mixins' as lib-mixins with (
  $foo: #fff
);

.some-class {
  @include lib-mixins.cool-thing;
}
```

> One follow-up question, regarding significance of ordering: let's say that we have a `@mixin` in our `mixins` partial that specifies a default value for an argument that references a variable in our `variables` partial. e.g.:
> 
> ```scss
> // some-lib/_mixins.scss
> @use  './variables';
> 
> @mixin cool-thing($foo: $variables.foo) {
>   color: $foo;
> }
> ```
> 
> ```scss
> // some-lib/_variables.scss
> $foo: #000 !default;
> ```
> 
> Does that default value only get resolved at the time the `@mixin` is `@include`d?

Default argument values are evaluated at call-time, so this will use the overridden value of `$foo`.
