### ISSUE TITLE
Handling names when propagating config from an all-in-one module to individual components

### ISSUE THREAD

**Issue by kfranqueiro** [sass/language#24]
MDC Web has an all-in-one package, including an [scss file](https://github.com/material-components/material-components-web/blob/v0.40.0/packages/material-components-web/material-components-web.scss) which currently imports all of the individual component packages and emits all their styles.

I suspect this gets far more use via its distributed CSS rather than running it through a preprocessor, but if someone were to `@use` this file, IIUC if we were to `@forward` each of the individual MDC package imports, it would also forward any `with` configuration to all of them?

This raises a potential question in terms of namespacing `with` configuration. For example, the names `primary` and `secondary` make sense when directly consuming `@material/theme` (referring to primary and secondary theme colors), but may be ambiguous in the context of the entire `material-components-web` library.

This probably seems like an edge case, but has any thought been given to some way to map variable names when `@forward`ed?

**Comment by nex3** [comment]
I thought about adding renaming to `@forward`, but as you say, it's enough of an edge case that I didn't think it was worth the extra syntax. For mixins and functions, it's easy to forward in the body of the module, so it would *only* be necessary for variables. If this is an important use-case for you, though, we can reconsider.

**Comment by kfranqueiro** [comment]
The more I think about this, the more I can foresee the all-in-one module story seeming awkward whether we renamed input/output between the single module and each separate package or not. Maybe the transition to Sass modules means that the only purpose the all-in-one module serves is to provide distributable precompiled CSS (and thus the configuration doesn't matter), and our story for Sass usage should focus on using individual modules directly, foregoing this case.

I've posted a question on our discord to see whether any users who consume and build our Sass are using the all-in-one module right now, to try to get an idea of whether this would be likely to cause any serious migration effort for our users.

More thoughts below in case they offer any food for thought (since I started spelling them out before coming to the above conclusion). Feel free to close this if you think it doesn't warrant any further action right now, but also feel free to correct me if any of my thoughts below seem like a misunderstanding.

---

Your mention of mixins and functions sounds like it might be referring to output moreso than input. My original concern was specifically over potential ambiguity or collisions of variable names supplied in `with`, i.e. as input/configuration variables to forwarded modules. Reusing the `primary` and `secondary` example above, they might not conflict with anything, but they might seem ambiguous in that they specifically apply as input to `@material/theme` forwarded via the all-in-one module.

I hadn't really considered the output case, figuring that our users are most likely to want to `@use` specific modules containing the mixins/functions they need for their customizations anyway. In order to support this, we would need to `@forward` our `_mixins.scss` etc. partials through each component's entry point first (assuming it's possible to both `@forward` and `@use` the same thing?) to even make them available via the all-in-one module (e.g. `@material/button/mixins` partial -> `@material/button/mdc-button` entry point -> `material-components-web/material-components-web` all-in-one). If we did this, there would certainly be potential for conflicts on the all-in-one _output_ as well (for example, assuming that we renamed every `mdc-foo-shape-radius` mixin to just `shape-radius` within its respective package).

It also occurs to me that `@forward`ing would presumably at least be necessary for `variables` partials anyway, in order to properly pass configuration from the all-in-one module.

Regarding the possibility of output conflicts, am I right to assume nested namespaces are not a thing?

**Comment by nex3** [comment]
You're right that nested namespaces aren't a thing. If you *were* to expose an all-in-one file that's meant to be `@use`d, you'd probably want to rename mixins like `shape-radius` to `foo-shape-radius`.

I do generally like the idea of supplying an all-in-one module, particularly because it avoids the need for your users to manually order their `@use`s as you mention in https://github.com/sass/language/issues/23#issuecomment-428999577. So maybe that does suggest that renaming should be part of `@forward`.

What do you think of syntax like
```scss
@forward "material/button/mdc-button" show shape-radius as button-shape-radius;
```

**Comment by kfranqueiro** [comment]
Would it be unreasonable to imagine `@forward '...' show * as button-*` for brevity and consistency across all of the transitive module's members?

Also, there's still the question of the input side of things, too, which might benefit from the reverse.

e.g. you might `@use` the top-level like this:

```scss
@use 'material-components-web/material-components-web' with (
  $theme-primary: ...,
  $theme-secondary: ...
);
```

but in direct use, `mdc-theme` would just accept `$primary` and `$secondary` because in that context `theme` is redundant (and other packages would behave similarly with its own configuration), so the all-in-one module would need to do something like...

```scss
@forward `mdc-theme` show * as theme-* with theme-* as *;
```

I realize this might be pie-in-the-sky and asking too much, but just wanted to throw the idea out there. (I also realize `with` currently isn't a thing for `@forward`, but I used `with` since it's applying a mapping that affects `@use ... with`.)

**Comment by nex3** [comment]
We could probably do `show * as button-*`, yeah. I don't think we'd need to have an equivalent `with` statement; as long as `@forward` forwards/renames variables, `with` should just work with the new names.

**Comment by nex3** [comment]
@kfranqueiro Can you help me understand the use-case behind this:

```
@forward `mdc-theme` show * as theme-* with theme-* as *;
````

**Comment by kfranqueiro** [comment]
I might be sort of repeating my earlier comments in trying to answer this question, so apologies in advance.

The use case is to prevent naming collisions between different modules rolled up into the all-in-one module. I'll explain each half individually.

`show * as theme-*` would disambiguate all members output by the individual component module as perceived through `@use`ing the all-in-one module - e.g. if you were to `@use 'material-components-web/material-components-web'`, you would access theme members via `material-components-web.theme-foo`, whereas if you were to `@use '@material/theme'` directly, you would access its members via `theme.foo`.

`with theme-* as *` would disambiguate all variables being input _into_ the all-in-one module to automatically send all theme-related variables to the theme module unprefixed.

e.g. `@use 'material-components-web/material-components-web' with ($theme-primary: blue)` would equate to `@use '@material/theme' with ($primary: blue)`.

In your last comment it sounded like you thought the `with` part would be redundant due to the nature of `@forward`? I took this to mean that `show * as theme-*` would already imply that the variables would similarly be renamed, and thus to override them you would already need to follow the new prefixed name.

**Comment by nex3** [comment]
Ah, I think I understand now.

> In your last comment it sounded like you thought the `with` part would be redundant due to the nature of `@forward`? I took this to mean that `show * as theme-*` would already imply that the variables would similarly be renamed, and thus to override them you would already need to follow the new prefixed name.

Yeah, that's right. As far as any users of `material-components-web` are concerned, the theme variable always has the same name whether it's being accessed, set, or configured using `with`.
