### ISSUE TITLE
Function tweaks

### ISSUE THREAD

**Issue by nex3** [sass/language#33]
I think some functions should be renamed, moved around, or otherwise tweaked in the new module system:

* `unitless()` should be called `is-unitless()`, to match `is-bracketed()` and to make it clear that it doesn't return the number stripped of units.
* `comparable()` should be called `compatible()`, to make it clear that it also tests for compatibility for addition and subtraction.
* `content-exists()` is currently missing and should be included.
* `unique-id()` should be in `sass:string` rather than `sass:meta`.

**Comment by nschonni** [comment]
>     * `comparable()` should be called `compatible()`

Not sure if that is clearer to me. Search around https://en.wikipedia.org/wiki/Addition to see if I could find anything 😛 . Only thing that came to mind would be to split them if you want to be super clear to `is-addable`/`is-subtractable` if it doesn't check for any other arithmetic comparability (multiply or divide).

**Comment by nschonni** [comment]
💯 I can see why `comparable` isn't a good name if it only lets you see about arithmetic operations. It was more that `compatible` didn't jump to mind as a something I'd look for if searching for a function for that purpose. Also agree that even if those functions all alias'd the same thing, it would be confusing.
`</bikesheding>`
