### ISSUE TITLE
Should extensions affect downstream modules?

### ISSUE THREAD

**Issue by nex3** [sass/language#6]
Draft 2 of the proposal says

> Extension is scoped to CSS in [module](#module)s *transitively used* by or *transitively using* the module in which the `@extend` appears.

The original goal of this behavior was to allow downstream stylesheets to override upstream style rules. The idea was that if an upstream selector specified `.error`, and extended it with `.error-intense`, any modification the stylesheet did to `.error` would affect `.error-intense` as well.

However, this approach also creates a problem for the downstream author. It should generally be safe to take a bunch of style rules from one module and split them into multiple modules that are all imported by that module. But under the Draft 2 semantics, this change would cause those styles to stop being affected by upstream extensions.

The existing approach also means that the semantics of a downstream author's styles are affected by the specific extensions used in an upstream stylesheet. That means that `.foo { ... } .bar { @extend .foo }` isn't identical (from a downstream user's perspective) to `.foo, .bar { ... }`. That could be a drawback or a benefit, but I suspect upstream authors generally think of themselves as distributing a chunk of styles rather than an API consisting of things they've extended.

I can see three ways to address this:

1. Keep the behavior as specified in Draft 2, and make factoring out downstream styles a potentially breaking change.

2. Allow extensions to affect modules used by downstream modules--that is, get rid of scoping entirely and keep `@extend` global.

3. Only allow extensions to affect upstream stylesheets.

I favor option 3 for the reasons outlined above, but I want to get other peoples' opinions.

**Comment by jelbourn** [comment]
I would land strongly on option 3. I see this as the most explicit, predictable behavior because it follows the thinking that the output of any given file is only affected by the contents of that file (including its `@use` statements). 

I would actually go even one step further here, based on [my proposal in #9](https://github.com/sass/language/issues/9#issuecomment-423637221): `@extend` should specify where the target of extension comes from. Ignoring specifics of syntax, I imagine this looking _conceptually_ something like
```scss
@use "vessel";

.cool-boat {
  @extend vessel.css(.speedboat);
}
```

Similarly to my comment on #9, the goal here is around making things more explicit. For example, say you have two different modules that both define a `.speedboat` class. By explicitly targeting the `@extend` statement, you get full control over what you're using:
```scss
@use "vessel";
@use "marine";

.cool-boat {
  @extend marine.css(.speedboat);
}
```

**Comment by nex3** [comment]
The idea of explicit extensions is intriguing, but I worry that enforcing it would add a lot of boilerplate for users writing application stylesheets that are distributed across many files for organizational purposes. To take an example from the Sass site, they may need to write:

```scss
@use "../regions/banner";
@use "../styleguide/guide";

#header {
  @extend banner.css(.banner), guide.css(.banner);
}
```

And even this is fragile in that `.banner` may be styled elsewhere and never overridden.

A more backwards-compatible option would be to *allow* extensions to be scoped, and then let teams opt into a stricter mode where scopes are required:

```scss
@use "vessel";
@use "marine";

.cool-boat {
  @extend .speedboat in marine;
}
```

This is something that's largely orthogonal to the module system, though.

**Comment by jelbourn** [comment]
I like that idea quite a bit. 

I was thinking it ties into the module system in that it's about how you reference constructs from other modules now that there's a direct handle to them.

**Comment by nex3** [comment]
> I was thinking it ties into the module system in that it's about how you reference constructs from other modules now that there's a direct handle to them.

That's a good point... I guess what I meant was more, it's something we can do separately after the module system is completed. I've filed https://github.com/sass/sass/issues/2566 to track it.

**Comment by nex3** [comment]
Now that the module system proposal has been accepted, this has been definitively decided: **extensions don't affect downstream modules**.
